name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # or any version you are using
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        working-directory: ./
        run: npm install

      - name: Build packages
        working-directory: ./
        run: npm run build

      - name: Publish weavel-core
        working-directory: ./weavel-core
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies for weavel
        working-directory: ./weavel
        run: npm install

      - name: Build packages
        working-directory: ./
        run: npm run build

      - name: Publish weavel
        working-directory: ./weavel
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
